export const MODULE_NAME = 'pony';

export const ACTION_TYPES = {
  MAZE_DATA_FETCHED: `${MODULE_NAME}/MAZE_DATA_FETCHED`,
  PONY_MOVED: `${MODULE_NAME}/PONY_MOVED`,
  SET_DIALOG_VISIBILITY: `${MODULE_NAME}/SET_DIALOG_VISIBILITY`,
  SET_DIALOG_MESSAGE: `${MODULE_NAME}/SET_DIALOG_MESSAGE`,
  SET_CONTROLS_AVAILABLE: `${MODULE_NAME}/SET_CONTROLS_AVAILABLE`
};
